[manifest]
version = "0.0.1"
dump_lua = true
priority = 0

[[patches]]
[patches.regex]
target = "functions/UI_definitions.lua"
pattern = "            } or nil,"
position = "after"
payload = '''

            G.STAGE == G.STAGES.MAIN_MENU and {
              label = localize('b_pktr_poker'),
              tab_definition_function = G.UIDEF.poketro,
              tab_definition_function_args = from_game_over,
              chosen = _challenge_chosen
            } or nil'''
match_indent = true
times = 1
